// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "IM.Test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace IM {
namespace Test {

namespace {

const ::google::protobuf::Descriptor* TestMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestMsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_IM_2eTest_2eproto() {
  protobuf_AddDesc_IM_2eTest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "IM.Test.proto");
  GOOGLE_CHECK(file != NULL);
  TestMsg_descriptor_ = file->message_type(0);
  static const int TestMsg_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMsg, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMsg, buf_),
  };
  TestMsg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TestMsg_descriptor_,
      TestMsg::default_instance_,
      TestMsg_offsets_,
      -1,
      -1,
      -1,
      sizeof(TestMsg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMsg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMsg, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_IM_2eTest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TestMsg_descriptor_, &TestMsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_IM_2eTest_2eproto() {
  delete TestMsg::default_instance_;
  delete TestMsg_reflection_;
}

void protobuf_AddDesc_IM_2eTest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::IM::Base::protobuf_AddDesc_IM_2eBase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rIM.Test.proto\022\007IM.Test\032\rIM.Base.proto\""
    "\"\n\007TestMsg\022\n\n\002id\030\001 \001(\r\022\013\n\003buf\030\002 \001(\tb\006pro"
    "to3", 83);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "IM.Test.proto", &protobuf_RegisterTypes);
  TestMsg::default_instance_ = new TestMsg();
  TestMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_IM_2eTest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_IM_2eTest_2eproto {
  StaticDescriptorInitializer_IM_2eTest_2eproto() {
    protobuf_AddDesc_IM_2eTest_2eproto();
  }
} static_descriptor_initializer_IM_2eTest_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestMsg::kIdFieldNumber;
const int TestMsg::kBufFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestMsg::TestMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:IM.Test.TestMsg)
}

void TestMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TestMsg::TestMsg(const TestMsg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:IM.Test.TestMsg)
}

void TestMsg::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0u;
  buf_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

TestMsg::~TestMsg() {
  // @@protoc_insertion_point(destructor:IM.Test.TestMsg)
  SharedDtor();
}

void TestMsg::SharedDtor() {
  buf_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void TestMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestMsg_descriptor_;
}

const TestMsg& TestMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_IM_2eTest_2eproto();
  return *default_instance_;
}

TestMsg* TestMsg::default_instance_ = NULL;

TestMsg* TestMsg::New(::google::protobuf::Arena* arena) const {
  TestMsg* n = new TestMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TestMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:IM.Test.TestMsg)
  id_ = 0u;
  buf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool TestMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:IM.Test.TestMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_buf;
        break;
      }

      // optional string buf = 2;
      case 2: {
        if (tag == 18) {
         parse_buf:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_buf()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->buf().data(), this->buf().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "IM.Test.TestMsg.buf"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:IM.Test.TestMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:IM.Test.TestMsg)
  return false;
#undef DO_
}

void TestMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:IM.Test.TestMsg)
  // optional uint32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // optional string buf = 2;
  if (this->buf().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->buf().data(), this->buf().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "IM.Test.TestMsg.buf");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->buf(), output);
  }

  // @@protoc_insertion_point(serialize_end:IM.Test.TestMsg)
}

::google::protobuf::uint8* TestMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:IM.Test.TestMsg)
  // optional uint32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // optional string buf = 2;
  if (this->buf().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->buf().data(), this->buf().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "IM.Test.TestMsg.buf");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->buf(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:IM.Test.TestMsg)
  return target;
}

int TestMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:IM.Test.TestMsg)
  int total_size = 0;

  // optional uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // optional string buf = 2;
  if (this->buf().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->buf());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:IM.Test.TestMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TestMsg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TestMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:IM.Test.TestMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:IM.Test.TestMsg)
    MergeFrom(*source);
  }
}

void TestMsg::MergeFrom(const TestMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IM.Test.TestMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.buf().size() > 0) {

    buf_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.buf_);
  }
}

void TestMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:IM.Test.TestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestMsg::CopyFrom(const TestMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IM.Test.TestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMsg::IsInitialized() const {

  return true;
}

void TestMsg::Swap(TestMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestMsg::InternalSwap(TestMsg* other) {
  std::swap(id_, other->id_);
  buf_.Swap(&other->buf_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TestMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestMsg_descriptor_;
  metadata.reflection = TestMsg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TestMsg

// optional uint32 id = 1;
void TestMsg::clear_id() {
  id_ = 0u;
}
 ::google::protobuf::uint32 TestMsg::id() const {
  // @@protoc_insertion_point(field_get:IM.Test.TestMsg.id)
  return id_;
}
 void TestMsg::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:IM.Test.TestMsg.id)
}

// optional string buf = 2;
void TestMsg::clear_buf() {
  buf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& TestMsg::buf() const {
  // @@protoc_insertion_point(field_get:IM.Test.TestMsg.buf)
  return buf_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TestMsg::set_buf(const ::std::string& value) {
  
  buf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:IM.Test.TestMsg.buf)
}
 void TestMsg::set_buf(const char* value) {
  
  buf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:IM.Test.TestMsg.buf)
}
 void TestMsg::set_buf(const char* value, size_t size) {
  
  buf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:IM.Test.TestMsg.buf)
}
 ::std::string* TestMsg::mutable_buf() {
  
  // @@protoc_insertion_point(field_mutable:IM.Test.TestMsg.buf)
  return buf_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* TestMsg::release_buf() {
  // @@protoc_insertion_point(field_release:IM.Test.TestMsg.buf)
  
  return buf_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void TestMsg::set_allocated_buf(::std::string* buf) {
  if (buf != NULL) {
    
  } else {
    
  }
  buf_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buf);
  // @@protoc_insertion_point(field_set_allocated:IM.Test.TestMsg.buf)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Test
}  // namespace IM

// @@protoc_insertion_point(global_scope)
